eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
management:
  tracing:
    enabled: true  # Enable tracing
    sampling:
      probability: 1.0
  
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
okta:
  oauth2:
    issuer: https://dev-09599453.okta.com/oauth2/default
    audience: api://default
